buildDebArchAll defaultRunPythonChecks: true,
                defaultWbdevImage: 'registry.wirenboard.lan/contactless/devenv_test:trixie',
                defaultWbdevTestingSets: 'trixie',
                defaultDebianRelease: 'trixie',
                defaultCodestyleBranch: 'feature/trixie',
                defaultRunLintian: true,
                defaultAngryPylint: true,
                defaultRunCoverage: true,
                defaultCoverageMin: "71",
                defaultDoCoverallsReporting: true
